### PR TITLE
Add NJUNMT-pytorch

### PR DESCRIPTION
**Pull request by whr94621**

### CODE REVIEW

**Comment by whr94621** [comment]
https://github.com/whr94621/NJUNMT-pytorch
We implement both tensor2tensor(master) and dl4mt(dl4mt branch, will be merged soon)
Thank you :)

**Comment by jonsafari** [comment]
Please restore OpenNMT's copyright ownership in the project's LICENSE file (above your name in the file).

**Comment by whr94621** [comment]
Restored. 
Thank you :) (I am not familiar with licence)

**Comment by jonsafari** [comment]
No worries!

**Pull request merged**
